=== Uouonomaru/creating_best_party/src/main/resources/static/xml/compatibilities.dtd
<!ELEMENT compatibilities (compatibility+)>
<!ELEMENT compatibility (type, weakpoint+)>
<!ELEMENT type EMPTY>
    <!ATTLIST type t1 CDATA #REQUIRED>
    <!ATTLIST type t2 CDATA #IMPLIED>
<!ELEMENT weakpoint EMPTY>
    <!ATTLIST weakpoint type CDATA #REQUIRED>
    <!ATTLIST weakpoint level CDATA #REQUIRED>

=== Uouonomaru/creating_best_party/src/main/resources/static/xml/compatibilities.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE compatibilities SYSTEM "compatibilities.dtd">
<compatibilities>
    <compatibility>
        <type t1="Normal" t2="" />
        <weakpoint type="Combat" level="1" />
        <weakpoint type="Ghost" level="-2" />
    </compatibility>
    <compatibility>
        <type t1="Heating" t2="" />
        <weakpoint type="Heating" level="-1" />
        <weakpoint type="Water" level="1" />
        <weakpoint type="Leaf" level="-1" />
        <weakpoint type="Ice" level="-1" />
        <weakpoint type="Temblor" level="1" />
        <weakpoint type="Bug" level="-1" />
        <weakpoint type="Rock" level="1" />
        <weakpoint type="Steel" level="-1" />
        <weakpoint type="Fairy" level="-1" />
    </compatibility>
    <compatibility>
        <type t1="Water" t2="" />
        <weakpoint type="Heating" level="-1" />
        <weakpoint type="Water" level="-1" />
        <weakpoint type="Voltage" level="1" />
        <weakpoint type="Leaf" level="1" />
        <weakpoint type="Ice" level="-1" />
        <weakpoint type="Steel" level="-1" />
    </compatibility>
    <compatibility>
        <type t1="Voltage" t2="" />
        <weakpoint type="Voltage" level="-1" />
        <weakpoint type="Temblor" level="1" />
        <weakpoint type="Aviation" level="-1" />
        <weakpoint type="Steel" level="-1" />
    </compatibility>
    <compatibility>
        <type t1="Leaf" t2="" />
        <weakpoint type="Heating" level="1" />
        <weakpoint type="Water" level="-1" />
        <weakpoint type="Voltage" level="-1" />
        <weakpoint type="Leaf" level="-1" />
        <weakpoint type="Ice" level="1" />
        <weakpoint type="Poison" level="1" />
        <weakpoint type="Temblor" level="-1" />
        <weakpoint type="Aviation" level="1" />
        <weakpoint type="Bug" level="1" />
    </compatibility>
    <compatibility>
        <type t1="Ice" t2="" />
        <weakpoint type="Heating" level="1" />
        <weakpoint type="Ice" level="-1" />
        <weakpoint type="Combat" level="1" />
        <weakpoint type="Rock" level="1" />
        <weakpoint type="Steel" level="1" />
    </compatibility>
    <compatibility>
        <type t1="Combat" t2="" />
        <weakpoint type="Aviation" level="1" />
        <weakpoint type="Esper" level="1" />
        <weakpoint type="Bug" level="-1" />
        <weakpoint type="Rock" level="-1" />
        <weakpoint type="Mischief" level="-1" />
        <weakpoint type="Fairy" level="1" />
    </compatibility>
    <compatibility>
        <type t1="Poison" t2="" />
        <weakpoint type="Leaf" level="-1" />
        <weakpoint type="Combat" level="-1" />
        <weakpoint type="Poison" level="-1" />
        <weakpoint type="Temblor" level="1" />
        <weakpoint type="Esper" level="1" />
        <weakpoint type="Bug" level="-1" />
        <weakpoint type="Fairy" level="-1" />
    </compatibility>
    <compatibility>
        <type t1="Temblor" t2="" />
        <weakpoint type="Water" level="1" />
        <weakpoint type="Voltage" level="-2" />
        <weakpoint type="Leaf" level="1" />
        <weakpoint type="Ice" level="1" />
        <weakpoint type="Poison" level="-1" />
        <weakpoint type="Rock" level="-1" />
    </compatibility>
    <compatibility>
        <type t1="Esper" t2="" />
        <weakpoint type="Combat" level="-1" />
        <weakpoint type="Esper" level="-1" />
        <weakpoint type="Bug" level="1" />
        <weakpoint type="Ghost" level="1" />
        <weakpoint type="Mischief" level="1" />
    </compatibility>
    <compatibility>
        <type t1="Bug" t2="" />
        <weakpoint type="Heating" level="1" />
        <weakpoint type="Leaf" level="-1" />
        <weakpoint type="Combat" level="-1" />
        <weakpoint type="Temblor" level="-1" />
        <weakpoint type="Aviation" level="1" />
        <weakpoint type="Rock" level="1" />
    </compatibility>
    <compatibility>
        <type t1="Rock" t2="" />
        <weakpoint type="Normal" level="-1" />
        <weakpoint type="Heating" level="-1" />
        <weakpoint type="Water" level="1" />
        <weakpoint type="Leaf" level="1" />
        <weakpoint type="Combat" level="1" />
        <weakpoint type="Poison" level="-1" />
        <weakpoint type="Temblor" level="1" />
        <weakpoint type="Aviation" level="-1" />
        <weakpoint type="Steel" level="1" />
    </compatibility>
    <compatibility>
        <type t1="Ghost" t2="" />
        <weakpoint type="Normal" level="-2" />
        <weakpoint type="Combat" level="-2" />
        <weakpoint type="Poison" level="-1" />
        <weakpoint type="Bug" level="-1" />
        <weakpoint type="Ghost" level="1" />
        <weakpoint type="Mischief" level="1" />
    </compatibility>
    <compatibility>
        <type t1="Dragon" t2="" />
        <weakpoint type="Heating" level="-1" />
        <weakpoint type="Water" level="-1" />
        <weakpoint type="Voltage" level="-1" />
        <weakpoint type="Leaf" level="-1" />
        <weakpoint type="Ice" level="1" />
        <weakpoint type="Dragon" level="1" />
        <weakpoint type="Fairy" level="1" />
    </compatibility>
    <compatibility>
        <type t1="Mischief" t2="" />
        <weakpoint type="Combat" level="1" />
        <weakpoint type="Esper" level="-2" />
        <weakpoint type="Bug" level="1" />
        <weakpoint type="Ghost" level="-1" />
        <weakpoint type="Mischief" level="-1" />
        <weakpoint type="Fairy" level="1" />
    </compatibility>
    <compatibility>
        <type t1="Steel" t2="" />
        <weakpoint type="Normal" level="-1" />
        <weakpoint type="Heating" level="1" />
        <weakpoint type="Leaf" level="-1" />
        <weakpoint type="Ice" level="-1" />
        <weakpoint type="Combat" level="1" />
        <weakpoint type="Poison" level="-2" />
        <weakpoint type="Temblor" level="1" />
        <weakpoint type="Aviation" level="-1" />
        <weakpoint type="Esper" level="-1" />
        <weakpoint type="Bug" level="-1" />
        <weakpoint type="Rock" level="-1" />
        <weakpoint type="Dragon" level="-1" />
        <weakpoint type="Steel" level="-1" />
        <weakpoint type="Fairy" level="-1" />
    </compatibility>
    <compatibility>
        <type t1="Fairy" t2="" />
        <weakpoint type="Combat" level="-1" />
        <weakpoint type="Poison" level="1" />
        <weakpoint type="Bug" level="-1" />
        <weakpoint type="Dragon" level="-2" />
        <weakpoint type="Mischief" level="-1" />
        <weakpoint type="Steel" level="1" />
    </compatibility>
    <compatibility>
        <type t1="Heating" t2="Normal" />
        <weakpoint type="Heating" level="-1" />
        <weakpoint type="Water" level="1" />
        <weakpoint type="Leaf" level="-1" />
        <weakpoint type="Ice" level="-1" />
        <weakpoint type="Combat" level="1" />
        <weakpoint type="Temblor" level="1" />
        <weakpoint type="Bug" level="-1" />
        <weakpoint type="Rock" level="1" />
        <weakpoint type="Ghost" level="-2" />
        <weakpoint type="Steel" level="-1" />
        <weakpoint type="Fairy" level="-1" />
    </compatibility>
    <compatibility>
        <type t1="Water" t2="Normal" />
        <weakpoint type="Heating" level="-1" />
        <weakpoint type="Water" level="-1" />
        <weakpoint type="Voltage" level="1" />
        <weakpoint type="Leaf" level="1" />
        <weakpoint type="Ice" level="-1" />
        <weakpoint type="Combat" level="1" />
        <weakpoint type="Ghost" level="-2" />
        <weakpoint type="Steel" level="-1" />
    </compatibility>
    <compatibility>
        <type t1="Leaf" t2="Normal" />
        <weakpoint type="Heating" level="1" />
        <weakpoint type="Water" level="-1" />
        <weakpoint type="Voltage" level="-1" />
        <weakpoint type="Leaf" level="-1" />
        <weakpoint type="Ice" level="1" />
        <weakpoint type="Combat" level="1" />
        <weakpoint type="Poison" level="1" />
        <weakpoint type="Temblor" level="-1" />
        <weakpoint type="Aviation" level="1" />
        <weakpoint type="Bug" level="1" />
        <weakpoint type="Ghost" level="-2" />
    </compatibility>
    <compatibility>
        <type t1="Temblor" t2="Normal" />
        <weakpoint type="Water" level="1" />
        <weakpoint type="Voltage" level="-2" />
        <weakpoint type="Leaf" level="1" />
        <weakpoint type="Ice" level="1" />
        <weakpoint type="Combat" level="1" />
        <weakpoint type="Poison" level="-1" />
        <weakpoint type="Rock" level="-1" />
        <weakpoint type="Ghost" level="-2" />
    </compatibility>
    <compatibility>
        <type t1="Aviation" t2="Normal" />
        <weakpoint type="Voltage" level="1" />
        <weakpoint type="Leaf" level="-1" />
        <weakpoint type="Ice" level="1" />
        <weakpoint type="Temblor" level="-2" />
        <weakpoint type="Bug" level="-1" />
        <weakpoint type="Rock" level="1" />
        <weakpoint type="Ghost" level="-2" />
    </compatibility>
    <compatibility>
        <type t1="Esper" t2="Normal" />
        <weakpoint type="Esper" level="-1" />
        <weakpoint type="Bug" level="1" />
        <weakpoint type="Ghost" level="-1" />
        <weakpoint type="Mischief" level="1" />
    </compatibility>
    <compatibility>
        <type t1="Mischief" t2="Normal" />
        <weakpoint type="Combat" level="2" />
        <weakpoint type="Esper" level="-2" />
        <weakpoint type="Bug" level="1" />
        <weakpoint type="Ghost" level="-3" />
        <weakpoint type="Mischief" level="-1" />
        <weakpoint type="Fairy" level="1" />
    </compatibility>
    <compatibility>
        <type t1="Fairy" t2="Normal" />
        <weakpoint type="Poison" level="1" />
        <weakpoint type="Bug" level="-1" />
        <weakpoint type="Ghost" level="-2" />
        <weakpoint type="Dragon" level="-2" />
        <weakpoint type="Mischief" level="-1" />
